[package]
name = "char-device"
version = "0.6.2-alpha.0"
description = "Character Device I/O"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["io"]
categories = ["rust-patterns"]
repository = "https://github.com/sunfishcode/char-device"
exclude = ["/.github"]

[build-dependencies]
rustc_version = "0.4.0"

[dependencies]
async-std = { version = "1.10.0", optional = true }
tokio = { version = "1.8.1", optional = true, features = ["fs"] }
unsafe-io = "0.9.1"
io-lifetimes = { version = "0.3.0", default-features = false }

[target.'cfg(not(windows))'.dependencies]
rsix = "0.23.0"

[target.'cfg(windows)'.dependencies]
winapi-util = "0.1.5"

[dev-dependencies]
async-std = { version = "1.10.0", features = ["attributes"] }
tokio = { version = "1.6.0", features = ["io-util", "macros", "rt"] }

[features]
default = []
use_async_std = ["async-std", "unsafe-io/async-std", "io-lifetimes/async-std"]
use_tokio = ["tokio", "unsafe-io/tokio", "io-lifetimes/tokio"]

[badges]
maintenance = { status = "actively-developed" }
